-- Ad. 1
INSERT INTO POSTS (USER_ID, BODY) VALUES (1, "TEST POST");
COMMIT;
-- Ad. 2
UPDATE POSTS
SET BODY = "To delete"
WHERE BODY = "TEST POST";
COMMIT;
-- Ad. 3
DELETE FROM POSTS
WHERE BODY = "To delete";
COMMIT;
